site_name: Citation File Format (CFF)
copyright: Copyright &copy; 2017 - 2023 The Citation File Format project

nav:
  - About:
    - Background: about/index.md
    - Project: about/project.md
    - Governance: about/governance/index.md
    - Steering committee: about/governance/steering-committee.md
    - Code of Conduct: about/governance/code-of-conduct.md
    - Funding & support: about/funding.md
    - History: about/history.md
  - Documentation:
    - Schema guide: documentation/index.md
    - Tutorials: tutorials/index.md
    - FAQ: documentation/faq.md
  - Templates: templates.md
  - Create a CFF file: create.md
  - Validate your CFF file: validate.md
  - Tools: tools.md
  - Blog:
    - Blog: blog/index.md
    - <span class="md-status md-status--rss"/> RSS Feed: feed_rss_created.xml
# Theme configuration
theme:
  name: material
  custom_dir: overrides

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

      primary: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      primary: deep purple

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.top

plugins:
  - search
  - blog:
      blog_toc: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - external-markdown

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets
  - abbr
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/citation-file-format
      name: The Citation File Format GitHub organization
    - icon: material/rss
      link: feed_rss_created.xml
      name: RSS feed for the blog
  status:
    rss: "Subscribe to the blog RSS feed!"

extra_css:
  - stylesheets/extra.css
