site_name: Citation File Format (CFF)
copyright: Copyright &copy; 2017 - 2023 The Citation File Format project

nav:
  - About:
    - Project: about/project.md
    - Governance: about/governance/index.md
    - Steering committee: about/governance/steering-committee.md
    - Code of Conduct: about/governance/code-of-conduct.md
    - Funding & support: about/funding.md
    - Timeline: about/timeline.md
    - Publications: about/publications.md
    - How to cite: about/how-to-cite.md
  - Documentation:
    # - Overview: documentation/index.md
    - How-To:
      - Use CFF to:
        - Make software citable: documentation/how-to/use/make-software-citable.md
        - Make software more reusable: documentation/how-to/use/make-software-reusable.md
        - Cite your dependencies: documentation/how-to/use/cite-dependencies.md
        - Cite other work: documentation/how-to/use/cite-other-work.md
        - Let others cite a paper: documentation/how-to/use/preferred-citation.md
      - Create CFF files:  # documentation/how-to/create-cff-files.md
        - Using a web form: documentation/how-to/create/cffinit.md
        - Using templates: documentation/how-to/create/templates.md
        - Using an IDE: documentation/how-to/create/ide.md
        - Using GitHub: documentation/how-to/create/github.md
      - Validate CFF files: # documentation/how-to/validate-cff-files.md
        - Using the command line: documentation/how-to/validate/cffconvert.md
        - Using Python: documentation/how-to/validate/python-jsonschema.md
      - Convert CFF files: documentation/how-to/convert/cffconvert.md
      - Edit CFF files: documentation/how-to/edit/ide.md
      - Overview: documentation/how-to/index.md
    - Reference:
      - Schema reference: documentation/reference/index.md
  - Examples: templates.md
  # - Create a CFF file: create.md
  # - Validate your CFF file: validate.md
  - Tools & integrations: tools.md
  - Development:
    - Overview: development/index.md
    - Roadmap: development/roadmap.md
  - Blog:
    - Blog: blog/index.md
    - <span class="md-status md-status--rss"/> RSS Feed: feed_rss_created.xml

# Theme configuration
theme:
  name: material
  custom_dir: overrides
  logo: _assets/images/logo-white-circle.svg
  favicon: _assets/images/logo-white-circle.svg

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

      primary: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      primary: custom

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.top
    - content.code.copy
    - navigation.indexes

plugins:
  - search
  - blog:
      blog_toc: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - external-markdown

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.snippets
  - abbr
  - footnotes
  - markdown_include.include:
        base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - neoteroi.timeline
  - pymdownx.details

# hooks:
#   - hooks/schema_version.py

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/citation-file-format
      name: The Citation File Format GitHub organization
    - icon: material/rss
      link: feed_rss_created.xml
      name: RSS feed for the blog
  status:
    rss: "Subscribe to the blog RSS feed!"
  # schema_version: {schema_version}

extra_css:
  - stylesheets/extra.css
  - stylesheets/timeline.css
