site_name: Citation File Format (CFF)
copyright: Copyright &copy; 2017 - 2023 The Citation File Format project

nav:
  - About:
    - About: about/index.md
    - Governance: about/governance/index.md
    - Code of Conduct: about/governance/code-of-conduct.md
    - Funding & support: about/funding.md
    - History: about/history.md
  - Documentation:
    - Schema guide: documentation/index.md
    - Tutorials: tutorials/index.md
    - FAQ: documentation/faq.md
  - Templates: templates.md
  - Create a CFF file: create.md
  - Validate your CFF file: validate.md
# Theme configuration
theme:
  name: material
  custom_dir: overrides

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

      primary: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      primary: deep purple

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/citation-file-format
      name: The Citation File Format GitHub organization

extra_css:
  - stylesheets/extra.css
