site_name: Citation File Format

nav:
  - About:
    - About: about/index.md
  - Documentation:
    - Schema guide: documentation/index.md
    - Tutorials: tutorials/index.md
  - Templates: templates.md
  - Create CFF file: create.md
  - Validate CFF file: validate.md
# Theme configuration
theme:
  name: material

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

      primary: deep purple

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

      primary: deep purple

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

plugins:
  - search
