authors:
  sc:
    name: Citation File Format Steering Committee
    description: ""
    avatar: https://github.com/citation-file-format.png
  sdruskat:
    name: Stephan Druskat
    description: Creator of CFF
    avatar: https://github.com/sdruskat.png
  