name: validate-examples
on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: read

jobs:
  validate-examples:
    name: Validate CFF examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Validate example files
        run: |
            files=$(find ./docs/_assets/ -type f -name 'cff-*-example.md')
                for file in $files; do
                cat $file | head -n -1 | tail -n +2 > $file.cff
                echo "Validating $file.cff ..."
                uvx cffconvert --validate -i $file.cff || exit 1
            done
            cfffiles=$(find ./docs/_assets/ -type f -name 'cff-*-example.md.cff')
            for cfffile in $cfffiles; do
                echo "Deleting $cfffile ..."
                rm $cfffile
            done
            echo "Done."
